services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: teamavail:latest
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app:cached
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teamavail
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

